name: Build and Deploy (GH Pages)
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
        env:
          NODE_ENV: production
          CUSTOM_PUBLIC_PATH: /rich-to-html/
          VUE_APP_HOSTING: pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
